#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ldcstc-gif <https://github.com/ldcstc-gif>
# Author: ldcstc-gif — original work — https://github.com/ldcstc-gif/openclaw-free-deploy
#
# ------------------------------------------------------------------------------
# scripts/gen-checksums.sh
#
# Generate a SHA256SUMS manifest covering every file in the repo (a tamper-
# detection baseline). Anyone can later run `sha256sum -c SHA256SUMS` to confirm
# nothing was modified. For real tamper-EVIDENCE, sign the manifest with your
# own key so it cannot be silently regenerated by someone else:
#
#     ./scripts/gen-checksums.sh
#     gpg --armor --detach-sign SHA256SUMS        # produces SHA256SUMS.asc
#     # …then attach BOTH files to your GitHub Release.
#
# Verify (anyone):
#     sha256sum -c SHA256SUMS                      # integrity
#     gpg --verify SHA256SUMS.asc SHA256SUMS       # authenticity (your key)
#
# See docs/PROVENANCE.md for the full story.
# ------------------------------------------------------------------------------
set -Eeuo pipefail

# Move to repo root (this script lives in scripts/).
cd "$(dirname "$0")/.."

OUT=SHA256SUMS

# Pick a sha256 tool (Linux: sha256sum, macOS: shasum -a 256).
if command -v sha256sum >/dev/null 2>&1; then
  SHA() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1; then
  SHA() { shasum -a 256 "$@"; }
else
  echo "error: need sha256sum or shasum on PATH" >&2
  exit 1
fi

# List every file except VCS internals and the manifest/signature themselves.
# Prefer git's tracked-file list when inside a repo (most reproducible);
# fall back to find otherwise.
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  mapfile -t FILES < <(git ls-files | grep -vE '^(SHA256SUMS|SHA256SUMS\.asc)$' | sort)
else
  mapfile -t FILES < <(find . -type f \
      -not -path './.git/*' \
      -not -name 'SHA256SUMS' \
      -not -name 'SHA256SUMS.asc' \
      | sed 's|^\./||' | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "error: no files found to checksum" >&2
  exit 1
fi

: > "$OUT"
SHA "${FILES[@]}" >> "$OUT"

echo "Wrote $OUT (${#FILES[@]} files)."
echo "Next: gpg --armor --detach-sign $OUT   # then attach $OUT + $OUT.asc to your release"
