#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 ldcstc-gif <https://github.com/ldcstc-gif>
# Author: ldcstc-gif — original work — https://github.com/ldcstc-gif/openclaw-free-deploy
#
# ==============================================================================
# scripts/deploy-worker.sh — Deploy the reverse-proxy / webhook Worker.  (v2)
#
# Usage:
#   ./scripts/deploy-worker.sh <custom-domain> <hf-space-url> [worker-name]
#
# Example:
#   ./scripts/deploy-worker.sh bot.example.com https://forever-openclaw-bot.hf.space
#
# Optional env to enable webhook hardening (#2 #5):
#   WEBHOOK_SECRET=<same secret OpenClaw uses>   # enables secret-token check
#   TELEGRAM_IP_CHECK=1                          # enforce Telegram IP ranges
#   CF_ZONE_NAME=apex.tld                        # for multi-part TLDs (.co.uk)
#
# Prereqs: Node.js; `npx wrangler login` (or CLOUDFLARE_API_TOKEN for CI).
# ==============================================================================
set -Eeuo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <custom-domain> <hf-space-url> [worker-name]" >&2
  echo "Example: $0 bot.example.com https://forever-openclaw-bot.hf.space" >&2
  exit 2
fi

DOMAIN=$1
HF_URL=${2%/}
WORKER_NAME=${3:-openclaw-proxy}
WEBHOOK_PATH=${WEBHOOK_PATH:-/telegram-webhook}

if [[ -n "${CF_ZONE_NAME:-}" ]]; then
  ZONE=$CF_ZONE_NAME
else
  ZONE=$(awk -F. '{print $(NF-1)"."$NF}' <<< "$DOMAIN")
fi

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
WORKER_JS="${REPO_ROOT}/cloudflare/worker.js"
[[ -f "$WORKER_JS" ]] || { echo "ERROR: $WORKER_JS not found." >&2; exit 1; }

WRANGLER_TOML="${REPO_ROOT}/cloudflare/wrangler.toml"
cat > "$WRANGLER_TOML" <<EOF
# Auto-generated by deploy-worker.sh — overwritten on next run.
name = "${WORKER_NAME}"
main = "worker.js"
compatibility_date = "2024-11-01"

[[routes]]
pattern   = "${DOMAIN}/*"
zone_name = "${ZONE}"

[vars]
HF_SPACE_URL  = "${HF_URL}"
WEBHOOK_PATH  = "${WEBHOOK_PATH}"
TELEGRAM_IP_CHECK = "${TELEGRAM_IP_CHECK:-0}"
EOF

echo "==> Wrote ${WRANGLER_TOML}"
echo "    Route:    ${DOMAIN}/*  (zone: ${ZONE})"
echo "    Upstream: ${HF_URL}"
echo "    Webhook:  ${WEBHOOK_PATH}  (IP check: ${TELEGRAM_IP_CHECK:-0})"

cd "${REPO_ROOT}/cloudflare"

# Secrets (encrypted at CF). HF_SPACE_URL also lives in [vars] for `wrangler dev`.
echo "==> Setting HF_SPACE_URL secret…"
printf '%s' "$HF_URL" | npx --yes wrangler@3 secret put HF_SPACE_URL --name "$WORKER_NAME" 2>/dev/null \
  || echo "    (non-fatal: [vars] HF_SPACE_URL already set)"

if [[ -n "${WEBHOOK_SECRET:-}" ]]; then
  echo "==> Setting WEBHOOK_SECRET secret…"
  printf '%s' "$WEBHOOK_SECRET" | npx --yes wrangler@3 secret put WEBHOOK_SECRET --name "$WORKER_NAME" 2>/dev/null \
    || echo "    (non-fatal)"
else
  echo "==> WEBHOOK_SECRET not provided — webhook secret-token check DISABLED."
  echo "    For webhook mode, re-run with: WEBHOOK_SECRET=\$(cat ~/.openclaw/.webhook-secret) $0 ..."
fi

echo "==> Deploying Worker…"
npx --yes wrangler@3 deploy

cat <<EOF

✅ Worker deployed.
   Test proxy:   curl -I https://${DOMAIN}/healthz
   Dashboard:    https://dash.cloudflare.com/?to=/:account/workers/services/view/${WORKER_NAME}

DNS: add a proxied record for ${DOMAIN} (CNAME → 100:: or any value, orange cloud ON).

If using webhook mode, register it with Telegram now:
   PUBLIC_BASE_URL=https://${DOMAIN} ./scripts/set-webhook.sh
EOF
